id: repoguardian_pr_analysis
namespace: hackathon.repoguardian

triggers:
  - id: github_pr
    type: io.kestra.plugin.github.triggers.PullRequest
    repository: "{{ vars.github_repository }}"  # Set via Kestra variables or secrets
    events:
      - opened
      - synchronize

tasks:
  - id: analyze_pr
    type: io.kestra.plugin.scripts.python.Script
    script: |
      import os
      import sys
      import json
      
      # Add current directory to path for imports
      sys.path.insert(0, os.getcwd())
      
      from kestra_integration import analyze_pr_for_kestra
      
      # Get PR data from trigger context
      repo_owner = "{{ trigger.repository.owner }}"
      repo_name = "{{ trigger.repository.name }}"
      pr_number = {{ trigger.pullRequest.number }}
      
      # Analyze the PR
      print(f"Analyzing PR #{pr_number} in {repo_owner}/{repo_name}...")
      analysis = analyze_pr_for_kestra(repo_owner, repo_name, pr_number)
      print(f"Analysis result: {analysis}")
      
      # Output results as JSON for next task
      result = {
          "analysis": analysis,
          "repo_owner": repo_owner,
          "repo_name": repo_name,
          "pr_number": pr_number
      }
      print(json.dumps(result))
    outputs:
      - id: result
        type: STRING

  - id: decision
    type: io.kestra.plugin.scripts.python.Script
    needs:
      - analyze_pr
    script: |
      import os
      import sys
      import json
      
      sys.path.insert(0, os.getcwd())
      
      from kestra_integration import make_decision, execute_decision
      
      # Parse output from previous task
      # In Kestra, outputs are available via the outputs object
      previous_output = """{{ outputs.analyze_pr.result }}"""
      data = json.loads(previous_output)
      
      analysis = data["analysis"]
      repo_owner = data["repo_owner"]
      repo_name = data["repo_name"]
      pr_number = data["pr_number"]
      
      # Make decision
      decision = make_decision(analysis)
      print(f"Decision: {decision}")
      
      # Execute the decision
      result = execute_decision(decision, repo_owner, repo_name, pr_number, analysis)
      print(f"Action result: {result}")
      
      # Output final result
      final_result = {
          "decision": decision,
          "result": result,
          "pr_number": pr_number
      }
      print(json.dumps(final_result))
    outputs:
      - id: result
        type: STRING
